const r = $('Parse Request').first().json;
const c = $('Page Contract').first().json; const S = c.spec;
const md = String($input.first().json.page || '');
if (!md) throw new Error('Validate: no page text');
const issues = [];
const norm = s => String(s || '').toLowerCase().replace(/[^a-z0-9À-ɏ]+/g, ' ').trim();
const h1s = md.match(/^#\s+.+$/gm) || [];
const h2s = (md.match(/^##\s+.+$/gm) || []).map(h => h.replace(/^##\s+/, '').trim());
const h3s = (md.match(/^###\s+.+$/gm) || []).map(h => h.replace(/^###\s+/, '').trim());
const body = md.replace(/^#{1,6}\s+.*$/gm, ' ').replace(/^\|.*\|$/gm, ' ');
const words = body.replace(/\[([^\]]+)\]\([^\)]*\)/g, '$1').split(/\s+/).filter(Boolean);
const total = words.length;
if (h1s.length !== 1) issues.push('There must be exactly one H1 and it must read exactly: ' + r.h1 + '. Found ' + h1s.length + ' H1 lines.');
else if (norm(h1s[0].replace(/^#\s+/, '')) !== norm(r.h1)) issues.push('The H1 must read exactly: ' + r.h1);
const want = c.sections.map(s => s.h2);
const expected = c.expectedH2Count || want.length;
if (h2s.length !== expected) issues.push('The page must have exactly ' + expected + ' H2 headings: these ' + want.length + ' in this order, verbatim: ' + want.join(' | ') + (c.closing ? ', followed by one closing H2 whose heading follows this pattern: ' + c.closing.headingPatterns : '') + '. Found ' + h2s.length + ' H2 headings. Use ### for any subheading.');
else {
  want.forEach((h, i) => { if (norm(h2s[i]) !== norm(h)) issues.push('H2 number ' + (i + 1) + ' must read exactly: ' + h + ' (found: ' + h2s[i] + ')'); });
  if (c.closing && /^(conclusion|summary|final thoughts|closing thoughts|key takeaways|in summary|wrapping up|to sum up|overall|in conclusion)\b/i.test(h2s[h2s.length - 1])) issues.push('The closing H2 "' + h2s[h2s.length - 1] + '" is generic. Rename it following this pattern: ' + c.closing.headingPatterns);
}
if (/^####/m.test(md)) issues.push('Heading levels are skipped. Use H2 and H3 only.');
const secParts = md.split(/^##\s+/m).slice(1);
secParts.forEach((p, i) => { const n3 = (p.match(/^###\s+/gm) || []).length; const wc = p.replace(/^#{1,6}\s+.*$/gm, ' ').split(/\s+/).filter(Boolean).length; if (n3 === 1) issues.push('Section "' + (h2s[i] || i + 1) + '" has a single H3. Use at least two H3s in a section or none.'); if (n3 > 0 && wc < 150) issues.push('Section "' + (h2s[i] || i + 1) + '" is under 150 words and has H3s. Remove the H3s there.'); });
if (S.h3Mode === 'required' && h3s.length === 0) issues.push('This page type requires H3 subheadings: ' + S.h3Policy + '. Add them where the rule says, phrased as the sub-question or item each covers, in sentence case.');
if (S.h3Mode === 'none' && h3s.length > 0) issues.push('This page type uses no H3 subheadings. Fold the ' + h3s.length + ' H3 headings into the prose.');
if (total < S.wordsMin) issues.push('Total length is ' + total + ' words, minimum ' + S.wordsMin + '. Expand the thinnest sections with substance, not filler.');
if (total > Math.round(S.wordsMax * 1.15)) issues.push('Total length is ' + total + ' words, maximum ' + S.wordsMax + '. Tighten without deleting a required section.');
const ansText = (md.split(/^##\s+/m)[0] || '').replace(/^#\s+.*$/m, '').trim();
const ansWords = ansText.split(/\s+/).filter(Boolean).length;
if (S.answerParagraph && ansWords < 25) issues.push('The page must open with a direct answer paragraph of 40 to ' + S.answerMaxWords + ' words under the H1, before the first H2.');
if (S.answerParagraph && ansWords > S.answerMaxWords + 40) issues.push('The opening paragraph is ' + ansWords + ' words. Cut it to at most ' + S.answerMaxWords + ' and move the rest into the first section.');
const kw = String(r.coreKeyword || '').toLowerCase().trim();
if (kw) {
  const esc = kw.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  if (words.slice(0, 100).join(' ').toLowerCase().indexOf(kw) === -1) issues.push('The core keyword "' + r.coreKeyword + '" is missing from the first 100 words.');
  if (words.slice(-100).join(' ').toLowerCase().indexOf(kw) === -1) issues.push('The core keyword "' + r.coreKeyword + '" is missing from the last 100 words.');
}
const tableRows = (md.match(/^\|.+\|$/gm) || []).length;
if (S.tablesMin > 0 && tableRows < 3) issues.push('At least ' + S.tablesMin + ' markdown table is required. None was found.');
const urls = (md.match(/\]\((https?:[^\)\s]+)\)/g) || []).map(x => x.slice(2, -1));
const nu = u => String(u || '').replace(/\/$/, '').toLowerCase();
const host = u => { const m = nu(u).match(/^https?:\/\/(?:www\.)?([^\/]+)/); return m ? m[1] : ''; };
const rootHost = host(r.siteRootUrl); const cta = nu(r.ctaUrl); const ctaHost = host(r.ctaUrl);
const isCta = u => cta && nu(u) === cta;
const internal = urls.filter(u => !isCta(u) && ((rootHost && host(u) === rootHost) || (ctaHost && host(u) === ctaHost)));
if (internal.length) issues.push('Links to the client\'s own site are not written by this page (they are added later). Remove these links and keep the sentences: ' + internal.slice(0, 5).join(', '));
const ctaCount = urls.filter(isCta).length;
const lastPart = secParts.length ? secParts[secParts.length - 1] : '';
const closingIdx = (c.closingSectionIndex || secParts.length) - 1;
if (cta && ctaCount > 1) issues.push('The CTA link ' + r.ctaUrl + ' appears ' + ctaCount + ' times. Keep exactly one, in the closing section.');
if (cta && ctaCount === 1 && secParts.findIndex(p => p.indexOf(cta) !== -1 || p.toLowerCase().indexOf(cta) !== -1) !== closingIdx) issues.push('The CTA link ' + r.ctaUrl + ' sits outside the closing section. Move it into the last section.');
if (c.ctaMode === 'none' && ctaCount > 0) issues.push('This page has no CTA. Remove the link ' + r.ctaUrl + ' and keep the sentence.');
if (c.ctaMode === 'required' && cta && ctaCount === 0) issues.push('The CTA link ' + r.ctaUrl + ' is missing. End the closing section with the call to action linked to it.');
const ctaRe = /\b(schedule (a|your) |book (a|your) |contact us|get in touch|reach out|request (a|your) (quote|demo|call|consultation)|talk to (us|our team)|call us|sign up|get started today|start your (search|project|journey)|let'?s talk)\b/i;
secParts.forEach((p, i) => { if (i !== closingIdx) { const m = p.match(ctaRe); if (m) issues.push('Call to action language appears outside the closing section, in "' + (h2s[i] || i + 1) + '": "' + m[0] + '". Remove it there; the CTA lives in the closing section only.'); } });
if (c.ctaMode === 'none' && lastPart.match(ctaRe)) issues.push('This page has no CTA. Remove the call to action language: "' + lastPart.match(ctaRe)[0] + '".');
const external = urls.filter(u => !isCta(u) && !(rootHost && host(u) === rootHost));
if (S.citationsMin > 0 && external.length < S.citationsMin) issues.push('Only ' + external.length + ' external citations found, minimum ' + S.citationsMin + '. Cite sources from the Live Research tool only.');
if (/\]\(https?:/.test(ansText)) issues.push('There is a link in the opening paragraph. Move it into a body section.');
if (/^#{1,3}\s+.*\]\(/m.test(md)) issues.push('There is a link inside a heading. Remove it.');
const banned = ['leverage', 'robust', 'seamless', 'unlock', 'transform', 'delve', 'cutting edge', 'game changer', 'testament', 'elevate', 'harness', 'in todays', 'pivotal', 'crucial role', 'here\'s the thing', 'the bottom line', 'at the end of the day', 'it\'s worth noting', 'it is worth noting'];
const hits = banned.filter(w => new RegExp('\\b' + w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i').test(body));
if (hits.length) issues.push('Banned vocabulary present: ' + hits.join(', ') + '. Rewrite those sentences.');
const connectives = body.match(/(^|[.!?]\s+)(Additionally|Moreover|Furthermore|In addition|That said|Ultimately|In conclusion|In summary|Overall)\b,?/g) || [];
if (connectives.length > 2) issues.push('Sentences start with stacked connectives (' + connectives.length + ' found: Additionally, Moreover, Furthermore, In addition, That said, Ultimately, Overall). Connect those sentences by content and delete the connective.');
if (/[—–]/.test(md)) issues.push('Dashes of em or en type are present. Replace with full stops or commas.');
if (body.indexOf(';') !== -1) issues.push('Semicolons are present. Replace them.');
if (/!/.test(body.replace(/\]\([^)]*\)/g, ''))) issues.push('Exclamation marks are present. Replace them with full stops.');
if ((body.match(/\d[\d.,]*\s?%/g) || []).length && external.length === 0 && S.citationsMin > 0) issues.push('Percentages appear with no external citation. Source them or remove them.');
if (/START_ARTICLE|END_ARTICLE/.test(md)) issues.push('Marker text leaked into the page. Remove START_ARTICLE and END_ARTICLE.');
return [{ json: { page: md, issues, issueCount: issues.length, passed: issues.length === 0, totalWords: total, h2Count: h2s.length, h3Count: h3s.length, tableRows, ctaLinks: ctaCount, externalCitations: external.length, citedUrls: external } }];
